name: Generate Contribution Graph Animation

on:
  # Run automatically once per day
  schedule:
    - cron: "0 0 * * *"  # Run at midnight UTC every day
  
  # Allow manual workflow execution
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - master
      - main  # Including main for repositories that use main as default
    
jobs:
  generate:
    name: Generate Contribution Animation
    permissions: 
      contents: write  # Needed for pushing to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Increased timeout for potential network issues
    
    steps:
      - name: Generate GitHub contribution snake animation
        uses: Platane/snk/svg-only@v3
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      - name: Push generated SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
